**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [12]:
#Code here

a = np.nan + np.empty(10)
a[4] = 1
print(a)

[nan nan nan nan  1. nan nan nan nan nan]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [15]:
#Code here

a, b = map(int,input("Enter Two Numbers: ").split())
x = np.random.random((a,b))
print(x)
print(x.mean())

[[0.77390885 0.04179363 0.45152914]
 [0.42826998 0.70272988 0.91737111]]
0.5526004300331252


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [21]:
#Code here

def borderArray(a,b):
    
    x =  np.ones((a,b))
    x[1:3,1:3] = 0
    print(x)
    
borderArray(4,4)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [22]:
#Code here

np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here

# NO we can not. Identity Matrix have to be a square.

print(np.eye(3))

print(np.identity(4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [30]:
#Code here

a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [35]:
#Code here

a =  np.random.randint(1, 100, (10, 2))
p = np.array([2,3])

print (a)

np.sqrt(np.sum((a-p)**2 , axis = 1)).astype(int)

[[ 5 72]
 [83 70]
 [11 96]
 [71 20]
 [87 66]
 [85 17]
 [71 76]
 [94 71]
 [41  2]
 [17 81]]


array([ 69, 105,  93,  71, 105,  84, 100, 114,  39,  79])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
#Code here

a = np.unravel_index(100, (6,7,8))

print(a)

(np.int64(1), np.int64(5), np.int64(4))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [50]:
#Code here


a = input().strip().split()
np.array(a[::-1], dtype= np.float32)

array([7., 6., 5., 4., 3., 2., 1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [56]:
#Code here

a = np.array([])

a.size

0

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

def SoftMax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    
    s = np.sum(np.exp(arr))
    return np.exp(arr) / s


a = np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278])
print(SoftMax(a))

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [66]:
#Code here

def vertical_stack(*args):
    for i in args:
        if type(i) != np.ndarray:
            raise TypeError("Requires Numpy Array")
        
    return np.vstack(args)

a = np.arange(10).reshape(2,-1)
print("A", a)
b = np.repeat(1, 10).reshape(2,-1)
print("B", b)
c = np.random.random((2,5))
print("C", c)

vertical_stack(a,b,c)

A [[0 1 2 3 4]
 [5 6 7 8 9]]
B [[1 1 1 1 1]
 [1 1 1 1 1]]
C [[0.96640059 0.13731114 0.34715794 0.27930744 0.14461578]
 [0.98174952 0.61007674 0.37149238 0.89355699 0.45155342]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.96640059, 0.13731114, 0.34715794, 0.27930744, 0.14461578],
       [0.98174952, 0.61007674, 0.37149238, 0.89355699, 0.45155342]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [88]:
#Code here

def date_array(start: str, end: str):
    if type(start) != str or type(end) !=  str:
        raise TypeError
    
    total_days_of_month = {
    "01": 31, "02": 28, "03": 31, "04": 30, "05": 31, "06": 30,
    "07": 31, "08": 31, "09": 30, "10": 31, "11": 30, "12": 31
    }
    
    end = end.split("-")
    end_last = int(end[-1]) + 1 
    
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f"0{days_diff}" if days_diff < 10 else f"{days_diff}"
        next_month = int(end[-2]) + 1
        end[-2] = f"0{next_month}" if next_month < 10 else f"{next_month}"
        
    else:
        end[-1] = f"0{end_last}" if end_last < 10 else f"{end_last}"
    
    end = "-".join(end)
    return np.arange(start, end, dtype= "datetime64[D]")

date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [95]:
#code here

x = np.random.random((5,4))
print(x)

print(x.mean(axis = 1, keepdims = True))

print(x - x.mean(axis = 1, keepdims = True))

[[0.45006942 0.9735225  0.34776974 0.43476656]
 [0.22309057 0.1821062  0.60346415 0.39656015]
 [0.85649564 0.88689249 0.23270045 0.81562251]
 [0.20065173 0.90553234 0.15356486 0.46129736]
 [0.84860124 0.46007583 0.21068991 0.70255911]]
[[0.55153206]
 [0.35130527]
 [0.69792777]
 [0.43026157]
 [0.55548152]]
[[-0.10146263  0.42199045 -0.20376232 -0.11676549]
 [-0.1282147  -0.16919906  0.25215888  0.04525488]
 [ 0.15856787  0.18896472 -0.46522732  0.11769473]
 [-0.22960984  0.47527077 -0.27669671  0.03103579]
 [ 0.29311972 -0.0954057  -0.34479161  0.14707759]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [96]:
#Code here

a = np.arange(9).reshape(3,3)
a[:, [0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [99]:
#Code here

a =  np.arange(10)

a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [103]:
#Code here

a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [104]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2633,  113, 7333, 9274, 3066],
       [8393, 2317, 5651, 5514, 4120],
       [1042, 3835, 4765, 4703, 2974],
       [9123, 4471, 1174, 8908, 6508],
       [ 906, 7840, 6799, 5174, 5357],
       [2100, 7764, 1810, 2622, 9878],
       [5501, 2948, 3423, 4509, 4491],
       [3369, 6020,  906, 8660, 6979]], dtype=int32)

In [111]:
#Code here

print(arr1[:,::2])

print((arr1 - arr1.min()) / (arr1.max() - arr1.min()))

[[2633 7333 3066]
 [8393 5651 4120]
 [1042 4765 2974]
 [9123 1174 6508]
 [ 906 6799 5357]
 [2100 1810 9878]
 [5501 3423 4491]
 [3369  906 6979]]
[[0.25806452 0.         0.73937532 0.93814644 0.30240655]
 [0.84792627 0.22570405 0.5671275  0.5530978  0.41034306]
 [0.09513569 0.38115719 0.47639529 0.47004608 0.29298515]
 [0.92268305 0.44628776 0.10865335 0.90066564 0.65488991]
 [0.0812084  0.79129544 0.68469022 0.51827957 0.53701997]
 [0.20348182 0.78351254 0.17378392 0.25693804 1.        ]
 [0.55176651 0.29032258 0.33896569 0.45017921 0.44833589]
 [0.33343574 0.60491551 0.0812084  0.87526882 0.7031234 ]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [115]:
#Code here

def nthmax(arr, n):
    if n> len(arr):
        raise IndexError("N is way out of limit.")
    arr.sort()
    return arr[-n]

nthmax(np.array([12,34,40,7,1,0]), 3)

np.int64(12)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [119]:
#code here

a = np.array([1,2,3])

np.repeat(a,3)
np.tile(a,3)

np.hstack([np.repeat(a,3) , np.tile(a,3)])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])